<?php

namespace PointWeb\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMailRepository extends EntityRepository
{
}
