admin_contactmail:
    path:     /
    defaults: { _controller: "PointWebAppBundle:ContactMail:index" }

admin_contactmail_show:
    path:     /{id}/show
    defaults: { _controller: "PointWebAppBundle:ContactMail:show" }

admin_contactmail_new:
    path:     /new
    defaults: { _controller: "PointWebAppBundle:ContactMail:new" }

admin_contactmail_create:
    path:     /create
    defaults: { _controller: "PointWebAppBundle:ContactMail:create" }
    methods:  POST

admin_contactmail_edit:
    path:     /{id}/edit
    defaults: { _controller: "PointWebAppBundle:ContactMail:edit" }

admin_contactmail_update:
    path:     /{id}/update
    defaults: { _controller: "PointWebAppBundle:ContactMail:update" }
    methods:  [POST, PUT]

admin_contactmail_delete:
    path:     /{id}/delete
    defaults: { _controller: "PointWebAppBundle:ContactMail:delete" }
    methods:  [POST, DELETE]
